# LOCAL
GET http://localhost:8080/contacts

GET http://localhost:8080/contacts/682ca3c7d8a839696a6ed1ce







# PRODUCTION
GET https://three41-w01-task.onrender.com/contacts

GET https://three41-w01-task.onrender.com/contacts/682ca3c7d8a839696a6ed1d0
